### ISSUE TITLE
Performance of mPLUG-Owl

### ISSUE THREAD

**Issue by MAGAer13** [TencentARC/GVT#2]
Hi, nice work on Multimodal LLM. Would you mind adding [mPLUG-Owl](https://github.com/X-PLUG/mPLUG-Owl/) into your evaluation so we can better known it's power.

Thanks.

**Comment by daoyuan98** [comment]
Thank you for your advice! 

Yes, mPLUG-Owl is an impactful work. We will consider include it in our evaluation.

**Comment by MAGAer13** [comment]
Thanks. 😊
