### ISSUE TITLE
How to switch to other visual encoders?

### ISSUE THREAD

**Issue by ImKeTT** [TencentARC/GVT#7]
Great work, thanks for sharing the code.

I'm wondering how to reproduce the results in Table 1, 2, 3 in the paper, since there's seem no related instruction or code that enable the modification of all visual encoders mentioned in the paper.

**Comment by daoyuan98** [comment]
Thank you for your interest in our work. 

For other visual encoders, we mainly used their provided checkpoints. You may find the base size of the used checkpoints from the following links

CLIP:  https://github.com/openai/CLIP
DeiT:  https://github.com/facebookresearch/deit
Dino: https://github.com/facebookresearch/dino
DinoV2: https://github.com/facebookresearch/dinov2
MAE: https://github.com/facebookresearch/mae

RegionCLIP: https://github.com/microsoft/RegionCLIP
OwlViT: https://github.com/huggingface/transformers

FD: https://github.com/SwinTransformer/Feature-Distillation
EVA: https://github.com/liuxingbin/dbot

If you want to reproduce the results, you may follow our details in the appendix. We used language modeling loss for training on (cc3M + VG + COCO + SBU) + (instruction data curated from obj365 and openimagesv6) for 10k steps. The full detail can be found in Apendix A.1

Hope this helps!

**Comment by ImKeTT** [comment]
Appreciate the reply! You really saved me a ton of time 👍  

btw, maybe you can also integrate these instructions into the readme?
